name: push to vow repos
on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    push_to_api_repo:
        runs-on: ubuntu-latest
        container: pandoc/latex
        steps:
            - uses: actions/checkout@v2
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: "./api"
                  destination-github-username: "beyin-digital"
                  destination-repository-name: "vow-api"
                  user-email: salih.codes@gmail.com
                  target-branch: main
    push_to_client_repo:
        runs-on: ubuntu-latest
        container: pandoc/latex
        steps:
            - uses: actions/checkout@v2
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: "./client"
                  destination-github-username: "salihcodes"
                  destination-repository-name: "vow-client"
                  user-email: salih.codes@gmail.com
                  target-branch: main
